version: "2"
services:
  node:
    image: node:8
    volumes:
      - "./data:/data"
    working_dir: /data
    ports:
      - 8000:8000
      - 3001:3001
    command: >
      bash -c "npm i lite-server
      && npm run dev"

        