version: "3.9"

services:
  node:
    image: node:12
    working_dir: /data
    volumes:
      - "./data:/data"
    ports:
      - 8000:8000
    command: >
      bash -c "npm install -g json-server
      && json-server -H 0.0.0.0 -p 8000 -w db.json"

      